name: logman
description: A simple yet powerful logging package for Flutter apps with an integrated UI and an optional debug page.
version: 0.0.20
homepage: https://github.com/Sorcel-Tech/logman.dart

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:


